# Site settings
title: "Let me teach you how to be successful online"
description: "My name is Lyam and I'm here to share with you my knowledge and experience over 10 years of monetizing my blog."
url: "https://ltphuong.github.io/"  # Replace with your GitHub Pages URL
baseurl: ""  # Leave empty for user site; set to "/my-blog" for project site

# Theme settings
remote_theme: raviriley/agency-jekyll-theme

# Build settings
plugins:
  - jekyll-remote-theme